FROM mysql:8.0

COPY init.sql /docker-entrypoint-initdb.d/

ENV MYSQL_ROOT_PASSWORD=Jean-Michelle7845
ENV MYSQL_DATABASE=ReactBoilerplate
ENV MYSQL_USER=julien
ENV MYSQL_PASSWORD=Jean-Michelle7845

EXPOSE 3306
